name: MoreUtils CI
on:
  push:
  pull_request:
    branches-ignore:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-20.04
    steps:
      - name: Branch and collaborator info
        run: |
          echo Branch Name: ${{github.ref_name}} 
          echo Triggered by: ${{github.actor}}
          echo Event: ${{github.event_name}}

      - name: Checkout more-utils repo
        uses: actions/checkout@v3

      - name: Install python version 3.8
        uses: actions/setup-python@v3
        with:
          python-version: "3.8.*"
          cache: "pip"

      - name: Install more-utils and its dependencies
        run: |
          pip install ".[tests]"

      - name: Run tests with pytest
        run: python -m pytest --tb=native tests
